agent:
  id: auto

server:
  address: localhost:9000
  tls: true
  ca_cert: certs/ca.crt
  client_cert: certs/client.crt
  client_key: certs/client.key

watch:
  paths:
    - ./test-watch #change this (for now its for testing)
  recursive: true
  max_file_size_mb: 50
  exclude:
    - ".git"
    - ".*tmp"
    - ".*log"

events:
  include:
    - FILE_CREATE
    - FILE_MODIFY
    - FILE_DELETE
    - CHANGE_PERMISSION
    - CHANGE_OWNERSHIP

scan:
  on_reconnect: true