// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: event.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_UNKNOWN           EventType = 0
	EventType_FILE_CREATE       EventType = 1
	EventType_FILE_DELETE       EventType = 2
	EventType_FILE_MODIFY       EventType = 3
	EventType_CHANGE_PERMISSION EventType = 4
	EventType_CHANGE_OWNERSHIP  EventType = 5
	EventType_FILE_SCAN         EventType = 6 //sent on startup/reconnect for baseline verification
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "UNKNOWN",
		1: "FILE_CREATE",
		2: "FILE_DELETE",
		3: "FILE_MODIFY",
		4: "CHANGE_PERMISSION",
		5: "CHANGE_OWNERSHIP",
		6: "FILE_SCAN",
	}
	EventType_value = map[string]int32{
		"UNKNOWN":           0,
		"FILE_CREATE":       1,
		"FILE_DELETE":       2,
		"FILE_MODIFY":       3,
		"CHANGE_PERMISSION": 4,
		"CHANGE_OWNERSHIP":  5,
		"FILE_SCAN":         6,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

type FileEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hostname       string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os             string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	FilePath       string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	EventType      EventType              `protobuf:"varint,4,opt,name=event_type,json=eventType,proto3,enum=event.EventType" json:"event_type,omitempty"`
	OldHash        string                 `protobuf:"bytes,5,opt,name=old_hash,json=oldHash,proto3" json:"old_hash,omitempty"`
	NewHash        string                 `protobuf:"bytes,6,opt,name=new_hash,json=newHash,proto3" json:"new_hash,omitempty"`
	OldPermissions string                 `protobuf:"bytes,7,opt,name=old_permissions,json=oldPermissions,proto3" json:"old_permissions,omitempty"`
	NewPermissions string                 `protobuf:"bytes,8,opt,name=new_permissions,json=newPermissions,proto3" json:"new_permissions,omitempty"`
	UserId         uint32                 `protobuf:"varint,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId        uint32                 `protobuf:"varint,10,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Timestamp      int64                  `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileEvent) Reset() {
	*x = FileEvent{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEvent) ProtoMessage() {}

func (x *FileEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEvent.ProtoReflect.Descriptor instead.
func (*FileEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *FileEvent) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *FileEvent) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *FileEvent) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileEvent) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_UNKNOWN
}

func (x *FileEvent) GetOldHash() string {
	if x != nil {
		return x.OldHash
	}
	return ""
}

func (x *FileEvent) GetNewHash() string {
	if x != nil {
		return x.NewHash
	}
	return ""
}

func (x *FileEvent) GetOldPermissions() string {
	if x != nil {
		return x.OldPermissions
	}
	return ""
}

func (x *FileEvent) GetNewPermissions() string {
	if x != nil {
		return x.NewPermissions
	}
	return ""
}

func (x *FileEvent) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FileEvent) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *FileEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\x05event\"\xdf\x02\n" +
	"\tFileEvent\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12/\n" +
	"\n" +
	"event_type\x18\x04 \x01(\x0e2\x10.event.EventTypeR\teventType\x12\x19\n" +
	"\bold_hash\x18\x05 \x01(\tR\aoldHash\x12\x19\n" +
	"\bnew_hash\x18\x06 \x01(\tR\anewHash\x12'\n" +
	"\x0fold_permissions\x18\a \x01(\tR\x0eoldPermissions\x12'\n" +
	"\x0fnew_permissions\x18\b \x01(\tR\x0enewPermissions\x12\x17\n" +
	"\auser_id\x18\t \x01(\rR\x06userId\x12\x19\n" +
	"\bgroup_id\x18\n" +
	" \x01(\rR\agroupId\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\x03R\ttimestamp\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\x87\x01\n" +
	"\tEventType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0f\n" +
	"\vFILE_CREATE\x10\x01\x12\x0f\n" +
	"\vFILE_DELETE\x10\x02\x12\x0f\n" +
	"\vFILE_MODIFY\x10\x03\x12\x15\n" +
	"\x11CHANGE_PERMISSION\x10\x04\x12\x14\n" +
	"\x10CHANGE_OWNERSHIP\x10\x05\x12\r\n" +
	"\tFILE_SCAN\x10\x062C\n" +
	"\x10FileEventService\x12/\n" +
	"\rsendFileEvent\x12\x10.event.FileEvent\x1a\n" +
	".event.Ack(\x01B Z\x1egithub.com/Rassimdou/FIM/protob\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_event_proto_goTypes = []any{
	(EventType)(0),    // 0: event.EventType
	(*FileEvent)(nil), // 1: event.FileEvent
	(*Ack)(nil),       // 2: event.Ack
}
var file_event_proto_depIdxs = []int32{
	0, // 0: event.FileEvent.event_type:type_name -> event.EventType
	1, // 1: event.FileEventService.sendFileEvent:input_type -> event.FileEvent
	2, // 2: event.FileEventService.sendFileEvent:output_type -> event.Ack
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		EnumInfos:         file_event_proto_enumTypes,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
