// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: event.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileEventService_SendFileEvent_FullMethodName = "/event.FileEventService/sendFileEvent"
)

// FileEventServiceClient is the client API for FileEventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// service for sending file events
type FileEventServiceClient interface {
	SendFileEvent(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileEvent, Ack], error)
}

type fileEventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileEventServiceClient(cc grpc.ClientConnInterface) FileEventServiceClient {
	return &fileEventServiceClient{cc}
}

func (c *fileEventServiceClient) SendFileEvent(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileEvent, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileEventService_ServiceDesc.Streams[0], FileEventService_SendFileEvent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileEvent, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileEventService_SendFileEventClient = grpc.ClientStreamingClient[FileEvent, Ack]

// FileEventServiceServer is the server API for FileEventService service.
// All implementations must embed UnimplementedFileEventServiceServer
// for forward compatibility.
//
// service for sending file events
type FileEventServiceServer interface {
	SendFileEvent(grpc.ClientStreamingServer[FileEvent, Ack]) error
	mustEmbedUnimplementedFileEventServiceServer()
}

// UnimplementedFileEventServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileEventServiceServer struct{}

func (UnimplementedFileEventServiceServer) SendFileEvent(grpc.ClientStreamingServer[FileEvent, Ack]) error {
	return status.Error(codes.Unimplemented, "method SendFileEvent not implemented")
}
func (UnimplementedFileEventServiceServer) mustEmbedUnimplementedFileEventServiceServer() {}
func (UnimplementedFileEventServiceServer) testEmbeddedByValue()                          {}

// UnsafeFileEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileEventServiceServer will
// result in compilation errors.
type UnsafeFileEventServiceServer interface {
	mustEmbedUnimplementedFileEventServiceServer()
}

func RegisterFileEventServiceServer(s grpc.ServiceRegistrar, srv FileEventServiceServer) {
	// If the following call panics, it indicates UnimplementedFileEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileEventService_ServiceDesc, srv)
}

func _FileEventService_SendFileEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileEventServiceServer).SendFileEvent(&grpc.GenericServerStream[FileEvent, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileEventService_SendFileEventServer = grpc.ClientStreamingServer[FileEvent, Ack]

// FileEventService_ServiceDesc is the grpc.ServiceDesc for FileEventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileEventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event.FileEventService",
	HandlerType: (*FileEventServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "sendFileEvent",
			Handler:       _FileEventService_SendFileEvent_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "event.proto",
}
