package main

import (
	"io"
	"log"
	"net"

	"github.com/Rassimdou/FIM/proto"
	"google.golang.org/grpc"
)

// server implements the FileEvenrService interface generated by Probuf
type server struct {
	proto.UnimplementedFileEventServiceServer
}

// SendFileEvent receives the stream of file events from the agent
func (s *server) sendFileEvent(stream proto.FileEventService_SendFileEventServer) error {
	log.Println("New agent connected to steam...")

	for {
		//Read the next event from the steam
		event, err := stream.Recv()

		if err == io.EOF {
			//the agent closed the connection
			log.Println("Agent closed the steam.")
			return stream.SendAndClose(&proto.Ack{Success: true})
		}
		if err != nil {
			log.Printf("Error reading from stream: %v", err)
			return err
		}

		log.Printf("[SERVER] Event Received -> Host: %s | OS: %s | Action: %s | File: %s ", event.Hostname, event.Os, event.EventType, event.FilePath)
	}
}

func main() {
	//open a network port
	lis, err := net.Listen("tcp", ":9000")
	if err != nil {
		log.Fatalf("Failed to listen: %v", err)
	}

	grpcServer := grpc.NewServer()

	//attach my custom logic to the engine
	proto.RegisterFileEventServiceServer(grpcServer, &server{})

	//start accapting connections
	log.Println("FIM Central Server listening on : 9000")
	if err := grpcServer.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}
