package main

import (
	"io"
	"log/slog"
	"net"
	"os"

	"github.com/Rassimdou/FIM/proto"
	"google.golang.org/grpc"
)

// server implements the FileEvenrService interface generated by Probuf
type server struct {
	proto.UnimplementedFileEventServiceServer
	logger *slog.Logger
}

// SendFileEvent receives the stream of file events from the agent
func (s *server) SendFileEvent(stream proto.FileEventService_SendFileEventServer) error {
	s.logger.Info("New agent connected to stream")

	for {
		//Read the next event from the steam
		event, err := stream.Recv()

		if err == io.EOF {
			//the agent closed the connection
			s.logger.Info("Agent closed the stream")
			return stream.SendAndClose(&proto.Ack{Success: true})
		}
		if err != nil {
			s.logger.Error("Error reading from stream", "error", err)
			return err
		}

		//LOKI SHIPPER: output structured JSON
		s.logger.Info("file_event",
			slog.String("hostname", event.Hostname),
			slog.String("os", event.Os),
			slog.String("action", event.EventType.String()),
			slog.String("file_path", event.FilePath),
			slog.String("hash", event.NewHash),
		)
	}
}

func main() {
	//initialize structured logger
	jsonHandler := slog.NewJSONHandler(os.Stdout, nil)
	logger := slog.New(jsonHandler)

	//set it as the default logger for the server
	slog.SetDefault(logger)

	//open a network port
	lis, err := net.Listen("tcp", ":9000")
	if err != nil {
		logger.Error("Failed to listen", "error", err)
		os.Exit(1)
	}

	grpcServer := grpc.NewServer()

	//attach my custom logic to the engine
	proto.RegisterFileEventServiceServer(grpcServer, &server{logger: logger})

	//start accapting connections
	logger.Info("FIM Central Server listening on : 9000")
	if err := grpcServer.Serve(lis); err != nil {
		logger.Error("Failed to serve", "error", err)
		os.Exit(1)
	}
}
